let display state = 
  print_string " ---------------------------------------- \n";
  print_string "|                                        | \n";
  print_string "|                                        | \n";
  print_string "|                                        | \n";
  print_string "|                                        | \n";
  print_string "|                                        | \n";
  print_string "|                                        | \n";
  print_string "|                                        | \n";
  print_string "|                                        | \n";
  print_string " ----------------------------------------- \n";